Mc more user info 9
molly-clabotst/lmnop pull request #29
Opened 2020-04-29 01:39 UTC by molly-clabotst

#10 

New Categories are Favorite Artist, Show and Venue.

![image](https://user-images.githubusercontent.com/34037624/80553671-4ee2be00-8990-11ea-98d9-f1e45f4db77f.png)

2020-05-01 17:52 UTC, mekdeshub123 requested changes

2020-05-01 17:52 UTC, mekdeshub123 commented on .gitignore
> +venv
remove venv

2020-05-01 17:52 UTC, mekdeshub123 commented on .gitignore
> +.vscode
remove .vscode

2020-05-06 15:13 UTC, Di30an commented
Ran this locally and made all the necessary migrations. The website is running but I cannot modify from /user/profile/pk page. Is it like that on your end? I can modify and save in the admin console and save them however these are not showing up on the user page. 

![LMNOP_ADMIN_LOGIN ](https://user-images.githubusercontent.com/43485223/81193838-c310f900-8f70-11ea-8649-085bbfc05cd7.png)

Cannot seem to modify from the users page or show the information that was saved in the admin console. 


![LMNOP_WEB](https://user-images.githubusercontent.com/43485223/81193875-cd32f780-8f70-11ea-9eeb-f98fb3b956de.png)

2020-05-07 02:32 UTC, molly-clabotst commented
Yeah I'm adding that feature for the other branch that I'm working on. I forgot to switch branches when adding that code. I plan on cleaning up the branch. This branch is only for adding the extra user info to the model.

2020-05-08 14:46 UTC, Di30an commented
The modeling seems fine. However the last part of  issue #9  'A user will be able to view all of their information. Other users will be able to view public information (so not email, any other private fields).' 

This is what the /user/profile/<pk> looks like on my end. 

![image](https://user-images.githubusercontent.com/43485223/81417057-760f5d00-90ff-11ea-8167-c26d166e6f5b.png)

Ran git fetch before I checked out your branch this morning. Is there something that I am missing or something on my end?

2020-05-11 14:05 UTC, molly-clabotst commented
Yes! I forgot to change branches when I started working on 19

2020-05-11 16:50 UTC, Di30an commented
> Yes! I forgot to change branches when I started working on 19

So should we close this issue and merge it with issue 19? You can also check out old commits using git log and finding an old commit.

2020-05-13 03:19 UTC, merged